### ISSUE TITLE
peer to peer code review (19/5/2k22)

### ISSUE THREAD

**Issue by TahenyBELGUITH** [mavericks-db/capstone02#29]
Hi @team,

you're doing well, well done! 💯 

- DRY code 👍 
- Clean code 👍 
- well commented Readme file 👍 
- no linters error 👍 

 but it still a few changes we suppose you to make ♻️ 

- for the popup, we suggest blurring the background so that the user still focuses on that interface .
-  kindly try to check the functionality of the counter of likes

we like your innovation where you add new features to your project!

**Comment by mavericks-db** [comment]
Hi @TahenyBELGUITH! 😎  

Your suggestions are noted. Thanks.

![](https://media.giphy.com/media/Pnh0Lou03fv92J4puZ/giphy.gif)
